### ISSUE TITLE
sussy

### ISSUE THREAD

**Issue by tenseoverflow** [EmilArr/Configs#1]
Hetkel on see väga sussy mida sa teed. 
Ma ei saanud seda oma parabola thinkpad Z61m librebooted GNU/Linux kernel 3.10 (sest sellel ei ole uut iwd/iwctl intel wifi proprietary driverit peal) runit bedrock plan 9 from user space süsteemi peal tööle, palun paranda.

**Comment by EmilArr** [comment]
Mida sa tööle ei saanud?
Ma olen seda nüüd uuendanud nii, et vb proovid uuesti. Lisasin ka juhendi

**Comment by tenseoverflow** [comment]
sus

**Comment by EmilArr** [comment]
Ok.
